[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyneedle-pointer"
version = "0.1.0"
description = "Standard implementation of Semantic Pointers (L) for PyNeedle."
requires-python = ">=3.10"
dependencies = [
    "pyneedle-spec",
]

[tool.hatch.build.targets.wheel]
packages = ["src/needle"]

[tool.uv.sources]
pyneedle-spec = { workspace = true }